version: "3.4"
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: "/run/secrets/postgres-user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres-password"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/secrets/:/run/secrets

volumes:
  pg-data: